In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

user_show_matrix = []
with open('user-shows.txt') as f:
    data = f.read()
a = data.split('\n')
for item in a:
    temp = item.split(' ')
    user_show_matrix.append(temp)
r_matrix = user_show_matrix[:-1] 
r_matrix = np.array(r_matrix)

In [ ]:
# User-to-user Recommender System.

alex = r_matrix[499].reshape(1,563)
show_score_1 = np.zeros((1,100))

for j in range(100):
    score = 0
    for i in range(9985):
        user = r_matrix[i].reshape(1,563)
        cos_sim = cosine_similarity(alex, user)
        cos_sim_num = cos_sim[0][0]
        score = score + cos_sim_num * int(r_matrix[i,j])
    show_score_1[0,j] = score

In [76]:
show_score_1

array([[188.59095884, 569.41450915, 568.80711536, 186.24072722,
        253.15028009, 729.59185809, 218.79645718, 114.68402905,
        431.55765849, 757.6011181 , 489.35065638, 591.34561233,
        207.46147075, 557.54716924, 453.0295513 , 547.39671699,
        344.58153932, 455.34474982, 104.2195372 , 466.40427014,
        639.13754998, 297.62577544, 300.40175337, 210.27206227,
        130.50933071, 594.45184705, 172.30662382, 255.93240328,
        263.94341468, 321.6388011 , 108.37179798, 326.44840703,
        233.00434676, 127.61618964, 416.0280739 , 627.16286663,
        455.07164891, 132.95540117, 356.6420695 , 139.15286995,
        435.82398784, 357.47939487, 143.95838718, 560.3102567 ,
        449.38101439, 827.60129547, 622.76122641,  54.3300465 ,
        355.90024534, 128.47843307, 143.06936636, 158.75536858,
        170.90419013, 214.70097076, 404.76554336, 433.94858692,
        422.47372148, 311.32817886, 390.01829103, 661.06075267,
        784.7819589 ,  97.64569408, 698.

In [125]:
# Top 5 shows that have the highest similarity scores for Alex.
with open('shows.txt') as f1:
    show = f1.read()
all_show = show.split('\n')

r_score = show_score_1[0]
u2u_top_5 = r_score.argsort()[-5:][::-1]

for i in range(5):
    print(str(all_show[u2u_top_5[i]]) + ' with a score of ' + str(show_score_1[0][u2u_top_5[i]]))   

"FOX 28 News at 10pm" with a score of 908.4800534761246
"Family Guy" with a score of 861.175999287327
"2009 NCAA Basketball Tournament" with a score of 827.6012954743547
"NBC 4 at Eleven" with a score of 784.7819589039703
"Two and a Half Men" with a score of 757.6011181024223


In [77]:
# Item-to-item Recommender System

show_score_2 = np.zeros((1,100))
for j in range(100):
    item1 = r_matrix[:,j].reshape(1,9985)
    score = 0
    for itm in range(563):
        item2 = r_matrix[:,itm].reshape(1,9985)
        cos_sim = cosine_similarity(item1, item2)
        cos_sim_num = cos_sim[0][0]
        score = score + cos_sim_num * int(r_matrix[499,itm])
    show_score_2[0,j] = score


In [78]:
show_score_2

array([[15.16799039, 25.52647214, 25.81764515, 14.21732527, 17.5983246 ,
        28.6726676 , 14.76532297, 11.64191307, 21.63369623, 28.84972764,
        23.27533953, 24.60843577, 15.06020385, 23.77199458, 22.97657979,
        24.29467134, 20.17699228, 24.0721633 , 10.31334499, 22.92127216,
        27.9938319 , 19.05437648, 20.25909609, 14.62272946, 12.66150194,
        26.17072379, 13.59269147, 17.60714327, 17.50259646, 17.78692476,
        11.15368631, 21.46931873, 15.05385914, 12.56098362, 21.7676052 ,
        26.2564853 , 22.29295725, 14.41955548, 20.72130563, 15.83509503,
        22.30373561, 20.15247016, 14.49038734, 25.31920047, 22.68929349,
        29.22700156, 24.78745564,  7.22415726, 22.49552939, 12.68581339,
        12.25585392, 13.44373784, 13.79964784, 16.32661102, 19.74146477,
        23.30877592, 22.59430101, 18.15804809, 20.56887327, 27.65599488,
        29.39679777,  9.86333129, 27.71873252, 23.23089417, 27.32075257,
        25.94178055, 19.65208177, 23.82960559, 28.6

In [126]:
# Top 5 shows that have the highest similarity scores for Alex.
r_score_2 = show_score_2[0]
i2i_top_5 = r_score_2.argsort()[-5:][::-1]

for i in range(5):
    print(str(all_show[i2i_top_5[i]]) + ' with a score of ' + str(show_score_2[0][i2i_top_5[i]]))

"FOX 28 News at 10pm" with a score of 31.364701678342396
"Family Guy" with a score of 30.00114179887778
"NBC 4 at Eleven" with a score of 29.396797773402557
"2009 NCAA Basketball Tournament" with a score of 29.227001561500472
"Access Hollywood" with a score of 28.971277674055557


In [79]:
# Latent hidden model Recommender System
from scipy import linalg

U, s, Vh = linalg.svd(r_matrix)
U.shape,  s.shape, Vh.shape

((9985, 9985), (563,), (563, 563))

In [88]:
U_lr = U[:,:10]
Vh_lr = Vh[:10,:]

s_lr = np.zeros((10, 10))
for i in range(10):
    s_lr[i, i] = s[i] 

r_pred = np.dot(U_lr, np.dot(s_lr, Vh_lr))

In [157]:
r_pred_alex = r_pred[499,:100]

In [159]:
top_5 = r_pred_alex.argsort()[-5:][::-1]
top_5

array([63, 48, 20, 69, 17])

In [160]:
# Top 5 shows for Alex.
for i in range(5):
    print(str(all_show[top_5[i]]) + ' with a score of ' + str(r_pred_alex[top_5[i]]))

"Wow Wow Wubbzy" with a score of 0.6985227720420748
"Max and Ruby" with a score of 0.6547618180802611
"CBS Evening News" with a score of 0.6416619222606893
"Blue's Clues" with a score of 0.5877393095770018
"The Young and the Restless" with a score of 0.5608630598353632
